### ISSUE TITLE
Local volumes for etcd?

### ISSUE THREAD

**Issue by craig-willis** [nds-org/workbench-helm-chart#15] opened 2019-08-16 13:47 UTC
The GKE deployment PR assumes a dynamically provisioned PVC for etcd, otherwise no persistence.  We can do this on OpenStack with NFS, but have found problems in the past with etcd on an NSF mount. 

An alternative may be to upgrade to 1.14+ and use a local persistent volume. In this case, etcd would always be bound to a specific node on OpenStack, which is not necessarily a problem:

https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

**Comment by bodom0015** [comment] 2020-09-25 19:15
Duplicate of https://github.com/nds-org/workbench-helm-chart/issues/6

**Closed as completed by bodom0015** 2020-09-25 19:15 UTC
